apiVersion: v1
kind: Service
metadata:
  labels:
    service: profile
  name: profile
spec:
  type: NodePort
  ports:
  - name: profile
    port: 8080
    targetPort: 80
    nodePort: 30001
  selector:
    service: profile